### ISSUE TITLE
Error while trying to run code.

### ISSUE THREAD

**Issue by Zemotacqy** [chay2199/GitHeat#1]
![pic1](https://user-images.githubusercontent.com/28734169/40926210-52fcdfd6-6839-11e8-91de-3ac6a3e27437.JPG)
Do look to this issue.

**Comment by sahitpj** [comment]
The following issue is probably because you haven't installed the lxml parser for parsing the document.

You can solve it by either changing your parser to the default python parser - html.parser, or html5lib, or you could download the lxml package 

You could look this up if you wish 
https://stackoverflow.com/questions/24398302/bs4-featurenotfound-couldnt-find-a-tree-builder-with-the-features-you-requeste

**Comment by chay2199** [comment]
I made this in Jupyter Notebook. When I run this code in Jupyter Notebook then it works fine.
